### ISSUE TITLE
[TASK] Sprint2_FE_콘친 찾기 페이지_콘서트 목록 불러오기

### ISSUE THREAD

**Issue by JH8459** [codestates/ALL-CON#14]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [ ] 조회수, 임박예정 등록일 버튼 구현
2. [ ] 콘서트 목록 스크롤 구현
3. [ ] 콘서트 썸네일 클릭시 목록 창 최소화 애니메이션 & CSS 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint2`
- Urgency: `High`
