### ISSUE TITLE
[TASK] Sprint2_FE_메인 페이지_점보트론 포스터 조회수순, 임박예정순, 등록일순 정렬 기능

### ISSUE THREAD

**Issue by Esoolgnah** [codestates/ALL-CON#15]
### ISSUE
- Group:  `client`
- Type: `feature`

### TODO
1. [ ] 점보트론 포스터 조회수순 정렬 기능 구현
2. [ ] 점보트론 포스터 임박예정순 정렬 기능 구현
3. [ ] 점보트론 포스터 등록일순 정렬 기능 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint2_Bare Minimum`
- Urgency: `Low`
