### ISSUE TITLE
[TASK] Sprint2_FE_UI/UX_회원가입 모달 구현

### ISSUE THREAD

**Issue by joykim93** [codestates/ALL-CON#16]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 회원가입 모달 구현

### TODO
- [ ] 회원가입 모달
    - [ ] 로그인 버튼 구현
    - [ ] 닉네임 / 이메일 / 비밀번호 / 비밀번호 입력란 구현
    - [ ] 닉네임 중복확인 버튼 구현
       - [ ] 중복된 닉네임이 없을시, 닉네임 입력란 하단에 `사용가능한 닉네임입니다.` 문구 표시
       - [ ]  중복된 닉네임이 있을시, 닉네임 입력란 하단에 `이미 사용하고 있는 닉네임입니다.` 문구 표시
    - [ ] 이메일 인증하기 버튼 구현
       - [ ] 이메일 인증하기 버튼 클릭시, 인증번호 입력 모달 표시 
    - [ ] 전체 동의 및 약관 동의 체크박스 구현
    - [ ] 이용 약관 동의 및 개인정보 위탁 동의 클릭시, 약관 모달 표시
    - [ ] 가입하기 버튼 구현
    - [ ] 취소 버튼 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint2_Bare Minimum`
- Urgency: `Low`
