### ISSUE TITLE
[TASK] Sprint2_FE_메인 페이지_포스터 클릭 시 해당 콘서트 정보 렌더링 기능 (useEffect)

### ISSUE THREAD

**Issue by Esoolgnah** [codestates/ALL-CON#21]
### ISSUE
- Group:  `client`
- Type: `feature`

### TODO
1. [ ] 포스터 클릭 시 해당 콘서트 정보 렌더링 기능 (useEffect)
2. [ ] 예매하기 버튼 클릭 시 해당 페이지로 이동 기능 구현
3. [ ] 콘친 찾기 바로가기 버튼 클릭 시 콘친 찾기 페이지로 라우팅 기능(navigate)

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint2_Bare Minimum`
- Urgency: `Low`
