### ISSUE TITLE
[TASK] Sprint2_FE_UI/UX_비밀번호 찾기 모달 구현

### ISSUE THREAD

**Issue by joykim93** [codestates/ALL-CON#29]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 비밀번호 찾기 모달 구현

### TODO
- [ ] 비밀번호 찾기 모달
    - [ ] 인증번호 받기 버튼 구현
    - [ ] 취소 버튼 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint2_Bare Minimum`
- Urgency: `Low`
