### ISSUE TITLE
[TASK] Sprint2_BE_서버 세팅 (클라이언트, 서버, 데이터베이스)

### ISSUE THREAD

**Issue by joykim93** [codestates/ALL-CON#3]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 서버 세팅 (클라이언트, 서버, 데이터베이스)

### TODO
1. [ ] 클라이언트 S3 버킷 세팅
2. [ ] 서버 EC2 인스턴스 세팅
3. [ ] 데이터베이스 RDS 세팅

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint2_Bare Minimum`
- Urgency: `Low`
