### ISSUE TITLE
[TASK] Sprint2_FE_콘친 찾기 페이지_콘친찾기 게시물 상세페이지

### ISSUE THREAD

**Issue by JH8459** [codestates/ALL-CON#45]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 콘친찾기 게시물 상세페이지

### TODO
1. [ ] 게시글 클릭시 게시글 썸네일 최소화 애니메이션 & CSS 구현
2. [ ] 게시글 정보 표현된 게시물 페이지 구현
3. [ ] 게시글 정보 수정시 게시글 모달페이지에서 정보 수정
4. [ ] 게시글 콘친멤버 수정시 멤버수 미니모달창으로 수정

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint2`
- Urgency: `High`
