### ISSUE TITLE
[TASK] Sprint2_BE_회원가입 모달_회원가입 기능 구현

### ISSUE THREAD

**Issue by Esoolgnah** [codestates/ALL-CON#61]
### ISSUE
- Group:  `server`
- Type: `feature`

### TODO
1. [ ] 닉네임 중복확인 기능 [GET]
2. [ ] 인증하기 버튼 클릭시, 이메일로 인증번호 발송 [POST]
3. [ ] 회원가입 기능 구현 [POST]

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint2_Bare Minimum`
- Urgency: `Low`
