### ISSUE TITLE
[TASK] Sprint2_BE_UI/UX_콘친페이지 - 글쓰기 모달

### ISSUE THREAD

**Issue by joykim93** [codestates/ALL-CON#67]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 콘친페이지 - 글쓰기 모달

### TODO
- [ ] 콘친페이지 - 글쓰기 모달
    - [ ] [POST] 작성하기 버튼 클릭시, 글 정보(사진 / 제목 / 모집중인 콘친의 수 / 현재 모인 콘친의 수 / 글내용) 저장
    - [ ] [POST] 카메라 아이콘 클릭시, AWS bucket에 이미지 정보 저장
    - [ ] [GET] AWS bucket으로부터 저장된 이미지 조회 (미리보기 기능 구현)

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint2_Bare Minimum`
- Urgency: `Low`
