### ISSUE TITLE
[TASK] Sprint2_BE_Deploy_배포 기초 세팅

### ISSUE THREAD

**Issue by Esoolgnah** [codestates/ALL-CON#70]
### ISSUE
- Group:  `server`
- Type: `feature`

### TODO
1. [ ] 클라이언트 S3 버킷 세팅
2. [ ] 서버 EC2 인스턴스 세팅
3. [x] 데이터베이스 RDS 세팅

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint2_Bare Minimum`
- Urgency: `Low`
