### ISSUE TITLE
[TASK] Sprint2_BE_DataBase_콘서트 오픈 공지 정보 크롤링

### ISSUE THREAD

**Issue by JH8459** [codestates/ALL-CON#71]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] 검색 키워드 선정 (인터파크 티켓)
2. [x] 검색 키워드 선정 (YES24 티켓)
3. [x] 크롤링 TEST (인터파크 티켓)
4. [x] 크롤링 TEST (YES24 티켓)
5. [ ] 노드 스케쥴러 크롤링 자동화 구현

### Labels
- Estimated time: `E: 10h`
- Group : `server`
- Sprint: `Sprint2`
- Urgency: `High`
