### ISSUE TITLE
[TASK] Sprint2_BE_Deploy_도메인 구매 및 HTTPS 배포

### ISSUE THREAD

**Issue by Esoolgnah** [codestates/ALL-CON#72]
### ISSUE
- Group:  `server`
- Type: `feature`

### TODO
1. [x] 도메인 구매
2. [ ] AWS 도메인 연결 (Route 53)
3. [ ] AWS 클라이언트 HTTPS 구현 (CloudFront)
4. [ ] AWS 서버 HTTPS 구현 (로드밸런서)

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint2_Bare Minimum`
- Urgency: `Low`
