### ISSUE TITLE
[TASK] Sprint2_BE_UI/UX_프로필 수정 페이지

### ISSUE THREAD

**Issue by joykim93** [codestates/ALL-CON#73]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 프로필 수정 페이지

### TODO
- [ ] 프로필 수정 페이지
    - [ ] [GET] 닉네임 중복확인 기능
    - [ ] [PATCH] 수정완료 버튼 클릭시, 유저 프로필 정보 변경 (닉네임 / 자기소개 / 비밀번호)

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint2_Bare Minimum`
- Urgency: `Low`
