### ISSUE TITLE
[TASK] Sprint2_BE_UI/UX_유저 프로필 사진 수정 모달

### ISSUE THREAD

**Issue by joykim93** [codestates/ALL-CON#79]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 유저 프로필 사진 수정 모달

### TODO
- [ ] 유저 프로필 사진 수정 모달
    - [ ] [POST] 카메라 아이콘 클릭시, AWS bucket에 이미지 정보 저장
    - [ ] [GET] AWS bucket으로부터 저장된 이미지 조회 (미리보기 기능 구현)
    - [ ] [PATCH] 변경 버튼 클릭시, 유저 프로필 정보(사진) 변경

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint2_Bare Minimum`
- Urgency: `Low`
