### ISSUE TITLE
[TASK] Sprint2_FE_UI/UX_로그인 모달 구현

### ISSUE THREAD

**Issue by joykim93** [codestates/ALL-CON#9]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 로그인 모달 구현

### TODO
- [ ] 로그인 모달
    - [ ] 이메일 및 비밀번호 입력란 구현
    - [ ] 회원가입 하기 버튼 구현
    - [ ] 로그인 버튼 구현
       - [ ] 로그인 실패시, 오류메시지 표시 (비밀번호 입력란 하단에 빨간색으로)
    - [ ] OAuth 2.0 구현 (구글 / 카카오톡)
    - [ ] 비밀번호 찾기 버튼 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint2_Bare Minimum`
- Urgency: `Low`
